# Generated by Django 4.1.5 on 2023-01-30 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_home_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='requests',
            field=models.ManyToManyField(null=True, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
    ]
