# Generated by Django 4.1.5 on 2023-02-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.device'),
        ),
    ]
